### PR TITLE
Adds Laravel 6 support.

### PR DESCRIPTION
**Pull request by albertski**
The following changes allow this to be installed on Laravel 6.x.

The one thing I had to do is update my use statements in each of my migration classes (not sure if this is normal):

from:
```
use Illuminate\Support\Facades\Schema;
```
to:
```
use Fisharebest\LaravelFloats\Schema
```

### CODE REVIEW

**Comment by fisharebest** [comment]
> The one thing I had to do is update my use statements in each of my migration classes

You don't need to import the facade classes - the laravel autoloader does it for you automatically!

The mappings are defined here: https://github.com/laravel/laravel/blob/master/config/app.php#L221

This package overrides the default mapping here: https://github.com/fisharebest/laravel-floats/blob/master/composer.json#L39

But if you choose to import them, then you must obviously choose which `Schema` class you want.

**Comment by albertski** [comment]
I was thinking I didn't need to.  It should have autoloaded but it didn't for me. I even tried adding it to the aliases in app/config but it didn't work as well.  Maybe it is an issue with my version of Laravel (6.2).

**Comment by fisharebest** [comment]
>  Maybe it is an issue with my version of Laravel (6.2).

I haven't used Laravel 6 yet.  I guess I need to test it.

**Comment by fisharebest** [comment]
> You don't need to import the facade classes - the laravel autoloader does it for you automatically!

I have updated the README to mention this.

**Comment by fisharebest** [comment]
Tag 1.2.0 created.

**Pull request merged**
